# Innovation

테스트

The energy research and development (R&D) field has seen a great deal of recent activity in the development of new and renewable energy technology, as a critical source of future energy supplies[@stern2006].

Given the ever-increasing pace and complexity of technological innovation in the energy sector, monitoring technological changes has become of strategic importance. One of the most common techniques for technology monitoring is patent analysis, which enables the identification of technological trends over time. Patent analysis is one of the most prevalent methods used to analyze technological innovation. Patents are a good proxy measure for innovation activities---they have been used to assess the current state of firms' innovation efforts and to shape their future direction and support their R&D decision-making.

However, few previous studies have carried out patent analysis in the energy sector. This study aims to explore patterns of innovation and of evolution in energy technologies, particularly focusing on similarities and differences across technologies. For this purpose, we first defined the relevant energy technologies and extracted the associated patent data from the United States Patents and Trademark Office (USPTO) and then adopted six patent indices and developed six patent maps to analyze their innovation characteristics. We then clustered energy technologies with similar characteristics, so defining innovation categories, and analyzed the changes in these characteristics over time to define their evolution categories. As one of the few attempts to investigate the overall trends in the energy sector's innovation and evolution, this study is expected to help develop an in-depth understanding of the energy industry, which will be useful in establishing technology strategies and policy in this rapidly changing sector. [@lee2013]
