# Week 1

## Intro

-   `매주` 수업과 관련된 주요 개념 및 논문 1편 요약 제출 (분량 무관) - KLMS에 숙제 제출 및 강의자료 다운!/

    -   `금요일 자정까지 제출`

    -   모든 분들은 한 학기 2번씩 발표하게 됨 (5-7분)

    -   요약, 가설, 연구방법, 결과, 결론, 개인 의견

-   Midterm 10/21 휴강

-   **실제 시험은 11/18 or 11/25 (시험의 비중은 60%) - handwriting**

    -   서술 : 핵심 이론에 대한 설명 15문제

    -   에세이 : 주어진 기사에 숨겨있는 혁신원리, 이론을 찾아내고, 관련 현상 설명

-   **Final report**는 지금 신경 쓰지 마세요.

    -   특허 자료를 통해 수업시간에 배운 이론 실증

    -   제출 시 표절검사 결과 함께 제출 e.g., copykiller . 표절률 10\~15%까지 허용

    -   11월 정도에 기말 주제 공지 예정

## Why Do Firms Differ

-   혁신 역량의 차이

    -   디지털 경제는 기존 경제와 완전히 다르다. **디지털 기술의 속성**을 모르면 디지털 경제을 알 수 없다. 디지털은 한계체증을 한다(marginal utility, 한계체감이 제로로간다). -\> 그래서 플랫폼 기업들이 생긴다. 네이버가 고객 한명을 더 받는데 비용이 얼마나 들까? 거의 0 일것이다.

    -   테슬라가 노리는 것? 전기차 -\> OS게임. 안드로이드/IOS 처럼... 네비게이션을 사면 자동차를 주는 세상?

    -   삼천리자전거. 여태까지는 B2C에 최적화되었음. 하지만 디지털 경제의 공유사업을 통해 공유자전거가 생기고 나서 B2B가 되었음. Customer가 아닌 플랫폼 기업Business에 팔아야 하는 것임.

    -   디지털 위에서는 패러다임이 바뀐다. 그래서 기술경영이 중요. 기술(제조)과 경영.

-   혁신도 하나의 이론. Innovation Theories.

    -   세계 탑 저널은 혁신이론을 기반으로 좋은 페이퍼가 나오고 있음.

    -   **사회과학**은 누적 지식을 바탕으로 **원전(original text)**을 깔 수있음. 아담스미스의 국부론은 지금 시대에 맞지 않아! 라는 얘기 가능.

    -   혁신의 아버지 **조지프 슘페터.** 슘페터로 부터 시작. 미국 대공황. 그 시대는 사회주의 - 자본주의가 격동할 때며, 누가 정답인지 모를 때. 소련의 사회주의, 미국의 자본주의 둘 다 잘 살았고 두 체제의 우월성이 확연하지 않았음. 미국의 fordism을 다른 국가들이 보고 자본주의 체제를 따라가게 됨.

    -   케인즈 - 수요, 슘페터 - 공급. 케인즈 수요정책, 통화정책. 슘페터는 기업의 혁신. 케인즈 소득주도, 슘페터 혁신 성장론.

    -   혁신성장은 구조적으로 기업의 체질을 바꿔야 하기 때문에 효과를 보기에 오래 걸린다. 정권 초기에는 혁신 얘기를 하고, 정권 말기에는 숫자로 나타나야 하니까 수요/통화정책을 다룬다. 이념 얘기는 아니다.

    -   국가의 통화량을 얘기할 때 MV=PY. 통화량 법칙. 통화량을 높이면 GDP가 성장하는 것처럼 보인다. 국가적으로 볼 때 fake 쓰기 좋다.

        -   M: 통화량, V: 화폐유통속도(거의 상수), P:가격(물가상승률, 이자율), Y:생산량(GDP)

    -   시장은 한번도 완전한 적이 없다. 개입에 관해 결정하는 것이 정책. 정책은 어떻게 균형상태를 이끌어 갈 것인가. 시장이 실패하기 쉬운 곳에 정책이 많이 들어간다. 20년 전만 해도 자유주의 팽배하였으나, 지금은 변화함.

    -   **History of Innovation Studies 강의 슬라이드**

    -   

-   Science & Technology

-   In Social Science (Innovation study)

    -   혁신이론의 순서. 혁신연구는 과학에서 기술로 가고, 기술에서 사업화로 가야함. 과학을 통해 기술을 만들고, 기술을 통해 사업화를 이루어내야 함.

    -   과학의 주체는 어디? 대학. 과학의 측정? 논문으로. 과학을 기술로 바꾸는 역할? 기업 혹은 기업부설연구소. 기술의 측정? 특허. 출연연구소의 역할은 과학을-\> 기술로.

    -   Clarivate(Web of Science) KAIST 학생 사용 가능!! 제일 좋은 특허 사이트.

-   **다음주 숙제**

    -   **슘페터 가설이란?**

    -   **슘페터 가설과 관련된 논문 1편 요약 1p 이상**

# Week 2

## Classics of Innovation Studies

-   슘페터 가설은 정답이 없다. 그래서 여전히 논문주제로 나온다. 왜 이런 물음들이 던져진걸까..?

-   **아담 스미스** 전의 경제는 학문이 아니고, 신학과 철학, 정치 수준에 불과하였음. 수요 = 공급, 공식화 될 수 있는 걸 얘기한 사람이 아담스미스. 아담스미스가 경제**학**을만든 것임. 하나의 시장, 커뮤니티를 살펴보니 그 안에서 개인은 이기적인 마음으로 자유롭게 거래를 하는 것을 살펴봄. 모아놓고 보니 그 안에서 균형을 잡고, 전체의 후생이 증가한다는 걸 발견. **기본은 완전경쟁시장.**

-   **칼 막스**는 아담 스미스의 주장에 돌을 던짐.

-   대공황(1929, Great Depression)이 오는 원인? 수요와 공급의 사이클이 느리거나 멈췄을 때. 어디를 자극해서? 어디를 관심? 케인즈는 수요쪽. 슘페터는 공급(기업).

-   케인즈는 유효수요론 주장하면서 정부의 개입을 이야기함. - 소득주도. 왜냐하면 시장은 한번도 완전한 적이 없었기 때문. 케인즈는 기업 쪽에 관심이 없음. 수요쪽에만 관심을 가짐.

-   슘페터는 기업에서 혁신을 통해 수요 공급 사이클을 돌릴 수 있다고 말함. - 혁신성장론.

-   케인즈, 슘페터 모두 시장의 불완전성에는 동의

## Schumpeterian hypothesis

-   **Part II Can Capitalism Survive? Chapter 8 Monopolistic Practices**

::: callout-important
## 중간고사 시험 대비

-   **The Schumpeterian tradeoff revisited**[@nelson1982], **시험에 나옴!!!** **Table의 결과 정리해두면 좋을 것**

    -   기본적으로 슘페터의 가설 및 이론을 지지함.

    -   많은 경쟁자들이 있는 시장보다는 적은 경쟁자들이 있는 시장에서 혁신적인 활동이 일어나기 쉽다는 것을 보여줌.

    -   투자가 제한된 상황에서는 경쟁 시장이 혁신을 촉진하는 것 보다는 독점적 시장이 혁신을 촉진하는 것이 더 효과적임.

    -   **Table 1\~6 주요 내용 정리 필요**
:::

-   제품혁신, 공정혁신. cost reduction인지, 매출 상승인지에 따라 제품 or 공정 혁신이 달라질 수 있다.

-   first-mover와 follower의 R&D 비용 차이는 어마어마함.

## Paradigm

-   Thomas Kuhn, 패러다임의 변화. 믿음, 세계관을 포함하는 넓은 의미의 형이상학적 변화 정상과학(교과서의 변경)

-   Though the world does not change with a change of paradigm, the scientist afterwards works in a different world. "The Structure of Scientific Revolutions, p. 121."

```{mermaid}
flowchart LR 
  A(Anomalies) --> B(Crisis) 
  B(Crisis) --> C(Revolution)
  C(Revolution) --> D(Normal Science)
  D(Normal Science) --> A(Anomalies)
```

## General Purpose Technology

-   **범용기술.** 새로운 세대로의 기술적, 산업적 변화를 불러오는 혁신기술들의 최상단에 위치하는 기술로, 한 세대 산업혁명 안에서 많은 기술들의 뿌리로 인식될 수 있는 기술

-   산업혁명은 일반적으로 범용기술의 출현과 함께 시작되어 당시 산업구조의 혁신적 변화를 일으킴

-   Enabling Technology라고도 부르며, **산업간 확산성(Pervasiveness), 개선 가능성(Improvement), 혁신 촉진성(Innovation Spawning)**

## Assignment

-   **혁신의 원천 관련 논문( 공급, 수요, 사용자, 기술 디지털 등) 1편 요약**
-   혁신의 trigger, driving force? 기술인가 수요인가. source of innovation
-   Source of Innovation \[Where Don innovations Come From?\] 에 관련하여 과제를 제출하시면 됩니다.

# Week 3

## Source of Innovation

### Technology Push - 시험 준비!!!

-   Technology Push Model

-   Basic Science -\> Applied Science and Engineering -\> Manufacturing -\> Marketing

-   

### Demand Pull - 시험 준비!!!

### Seven sources of innovation

-   Unexpected, Incongruity, Market Structure, Necessity, Demographics, Changing Perception, New Knowledge

-   Descriptive, 통계 등을 활용해 증명을 해야 한다.

-   Prescriptive 처방적. 피터 드러커의 연구는 증명할 거리가 아니다. 처방적인 것은 측정하기가 너무 어렵다. 기껏해야 설문 조사. 처방적 얘기를 가지고 연구주제로 가기는 쉽지 않다. 마케팅이나 MBA에서 가능

-   **Gibbons Mode 1 to Mode 2 (중요!!!!!!!!!!!)**

### 과학-기술 연계성 분석

-   특허의 NPL(Non-Patent Literature) 특허에 있는 참고문헌 중 비특허문헌

### Assignment

::: callout-important
Types, Architecture and Taxonomy 관련 논문

(아티텍쳐 혁신, 모듈러 혁신, Pavitt 분류, 혁신의 분류)
:::

# Week 4

## Types and Patterns of Innovation

-   Product innovation

-   Process innovation

## Assignment

::: callout-important
## 이번주 과제는 두 개임

Process innovation과 Process innovation을 구분할 수 있는 방법? 정답은 없다. 아이디어 제출.

Product/Process innovation 다룬 논문 요약해서 제출
:::
